# Generated by Django 4.2 on 2024-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
