# Generated by Django 4.2 on 2025-02-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_name_alter_maincategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fifth_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.fifthcategroy'),
        ),
    ]
