# Generated by Django 4.2 on 2025-02-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_image_maincategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountedproduct',
            name='image_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
