# Generated by Django 4.2 on 2025-02-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoname',
            name='tech_info',
        ),
        migrations.RemoveField(
            model_name='technicalinfoname',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='infos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='info_name',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='tech_info',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='name',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='text',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='InfoName',
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
        migrations.DeleteModel(
            name='TechnicalInfoName',
        ),
    ]
