# Generated by Django 4.2 on 2025-02-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_discountedproduct_image_uz_product_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='1', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
