# Generated by Django 4.2 on 2025-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
