# Generated by Django 4.2 on 2025-03-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinfo',
            unique_together={('product', 'name')},
        ),
    ]
